### ISSUE TITLE
Checklist for Galactic Empires v2

### ISSUE THREAD

**Issue by ItsKodas** [ItsKodas/Horizons-Technologies#1]
## Balance & Costs
- [ ] Balance Tritium Efficiency
- [ ] Improve Tritium Block Costs
- [x] Improve Tiered Tech Block Costs

## Prismatics Balance & Development
- [ ] Balance Neodymium
- [x] Implement Carbon
- [x] Balance Prismatic Armor
